### ISSUE TITLE
HUBOT_OWM_APIKEY

### ISSUE THREAD

**Issue by Pitstopper** [skibish/hubot-weather#10]
Hi! The problem is that wherever I add an API Key plugin shows nothing other than this:
![screenshot-eaaa party-2018 10 29-12-24-44](https://user-images.githubusercontent.com/18574776/47641134-51374280-db76-11e8-8e38-0ead0c52a9e1.png)

I tried to add env. variables as you showed in the previous issue (export HUBOT_OWM_APIKEY=<CHANGE THIS TO YOUR API KEY>),  and set them manually in .profile or /etc/environment. The result is the same. As in the screenshot. Please help.

**Comment by skibish** [comment]
Hi @Pitstopper let's try to find out what is wrong. How you set environment variable and how you start hubot?

**Comment by Pitstopper** [comment]
Hi! Sorry for delay. I set the environment variable with the command `export  HUBOT_OWM_APIKEY = XXXXXXXX`, where XXXXXXXXX is the API-code issued after registering on the site. I tried to prescribe a variable environment manually in the files .profile, and then tried in /etc /environment. Even rebooted the server. Hubot runs as a service, version 3.1.1, adapter version 0.2.9.

**Comment by skibish** [comment]
You mentioned that you run it as a service:

Take a look on [this answer](https://unix.stackexchange.com/questions/44370/how-to-make-unix-service-see-environment-variables)

And [this article](https://coreos.com/os/docs/latest/using-environment-variables-in-systemd-units.html) about system services and environment variables.

Hope this will help!

**Comment by Pitstopper** [comment]
Thanks for the tip. I added a variable environment to the file /etc/systemd/system/hubot.service:

`; Hubot systemd service unit file
; Place in e.g. `/etc/systemd/system/hubot.service`, then `systemctl daemon-reload` and `service hubot start`.

[Unit]
Description=hubot
Requires=network.target
After=network.target

[Service]
Type=simple
WorkingDirectory=/var/www/hubot
User=root

Restart=always
RestartSec=10

; Configure Hubot environment variables, use quotes around vars with whitespace as shown below.
**Environment="HUBOT_OWM_APIKEY=XXXXXXXXXXXXXXXXXXX"**

; Alternatively multiple environment variables can loaded from an external file
;EnvironmentFile=/etc/hubot-environment

ExecStart=/var/www/hubot/bin/hubot

[Install]
WantedBy=multi-user.target
`
And it worked great! Thanks again for the tip!
