### ISSUE TITLE
Forecast in 5 days and RU localization

### ISSUE THREAD

**Issue by Pitstopper** [skibish/hubot-weather#11]
Hi! Having seen examples of api on the weather site, I saw an opportunity to make a forecast for 5 days and display data in different languages. The question is what needs to be upgraded in your code to use these features?

**Comment by skibish** [comment]
Hi @Pitstopper 

I think you are interested modifying the API call

https://github.com/skibish/hubot-weather/blob/b7d91ce4b20e1537420f64cae0214bfc3462b096/src/hubot-weather.coffee#L25
