### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by downright770** [skibish/hubot-weather#7]
Hi wondering as I'm new to this where do I change the API key. I have set up an account on the weather site and have a API key but not sure what file to change it in. 
Any help would be great.

**Comment by skibish** [comment]
Hi, @downright770 !

You don't need to change any file :)

You need to pass your key as environment variable. In Linux you can do it like (in terminal):

``` bash
export HUBOT_OWM_APIKEY=<CHANGE THIS TO YOUR API KEY>
```

or set it in `.profile` or `/etc/environment`.

**Comment by downright770** [comment]
Hi,
I tried the export HUBOT_OWM_APIKEY=<CHANGE THIS TO YOUR API KEY>

But still running into this error.
Sorta still new to linux sorry.

gizmo> gizmo weather in Calgary
gizmo> [Thu Oct 06 2016 13:04:17 GMT-0700 (PDT)] ERROR Error: EACCES: permission denied, open '.hubot_history'
  at Error (native)

HUBOT_OWM_APIKEY environment varibale is not provided for hubot-weather
Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.

**Comment by skibish** [comment]
@downright770 , try to do this (on Linux):

``` bash
# Open environment file
gizmo> sudo nano /etc/environment

# It will open file, write there:
HUBOT_OWM_APIKEY=<CHANGE THIS TO YOUR API KEY>

# save file, close terminal and open it

gizmo> echo $HUBOT_OWM_APIKEY

# It should output your API key
# Restart hubot to apply changes

```

**Comment by skibish** [comment]
@downright770, that solved the problem?
